# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [2]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [ ]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['bottom' '2' 'top' '2' 'top' 'top' 'top' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [ ]:
print(np.random.choice(10))

Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [ ]:
import numpy as np
print(np.random.choice(10, size=(4, 6)))

### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [4]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[0 2 0 3 1 4 0 3 1 2]


Згенеруйте одну випадкову цифру.

In [ ]:
# Місце для Вашого коду
print(np.random.randint(10))

Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [ ]:
# Місце для Вашого коду
print(np.random.randint(low = 10, high = 100, size=(4, 5)))

### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [ ]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [5]:
print(np.random.sample(size=(3,4)))

[[0.53274123 0.14190965 0.57338245 0.00227237]
 [0.6465066  0.49739318 0.59189703 0.84761254]
 [0.55511169 0.27834583 0.08197491 0.1472456 ]]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [7]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[5 4 1 3 2 8 9 6 7 0]


Перетасуйте матрицю $M$.

In [10]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Приклад

np.random.shuffle(M)
print(M)

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [11]:
print(np.random.randint(10))

4


In [ ]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [13]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['T' 'H' 'T' 'T' 'H' 'H' 'H' 'H' 'H' 'H']


In [14]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

7 heads and 3 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [ ]:
# Місце для Вашого коду

tosses = np.random.choice(["H","T"], size=100)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

48 heads and 52 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [ ]:
# Приклад

tosses = np.random.randint(2, size=100)
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

52 heads and 48 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [ ]:
# Приклад

tosses = np.round(np.random.sample(100))
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

50 heads and 50 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [ ]:
# Приклад

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for n in params:
    tosses = np.random.randint(2, size=n)
    heads_prob = sum(tosses == 1) / n
    tails_prob = sum(tosses == 0) / n
    print('n = {}  :  P(head) = {},  P(tail) = {}'.format(n, heads_prob, tails_prob))

n = 10  :  P(head) = 0.5,  P(tail) = 0.5
n = 50  :  P(head) = 0.46,  P(tail) = 0.54
n = 100  :  P(head) = 0.53,  P(tail) = 0.47
n = 250  :  P(head) = 0.456,  P(tail) = 0.544
n = 500  :  P(head) = 0.476,  P(tail) = 0.524
n = 1000  :  P(head) = 0.502,  P(tail) = 0.498
n = 2500  :  P(head) = 0.5004,  P(tail) = 0.4996
n = 5000  :  P(head) = 0.5026,  P(tail) = 0.4974
n = 10000  :  P(head) = 0.4983,  P(tail) = 0.5017


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [5]:
# Місце для Вашого коду
def find(arr, target):
  counter = 0
  for el in arr:
    if el == target:
      counter +=1
  return counter
t = np.random.randint(6, size=60)
print(t)
print(f'1 = {find(t, 0)} times, 2 = {find(t, 1)} times, 3 = {find(t, 2)} times')

[2 1 2 2 2 0 4 3 3 2 3 5 1 1 2 2 3 2 0 1 4 2 4 4 2 0 4 5 1 2 3 1 0 3 3 1 1
 1 0 3 4 5 4 1 4 3 0 3 4 2 1 3 2 2 0 3 0 0 4 1]
1 = 9 times, 2 = 12 times, 3 = 14 times


### <font color=blue>4.2 Задача</font>
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [23]:
#Домашнє завдання 1
for count in (10, 50, 100, 250, 500, 1000, 2500, 5000, 10000):
    t = np.random.randint(6, size=count)
    t = tuple(t)
    print(f'1 = {t.count(0)}, 2 = {t.count(1)}, 3 = {t.count(2)}, 4 = {t.count(3)}, 5 = {t.count(4)}, 6 = {t.count(5)}')

1 = 0, 2 = 1, 3 = 2, 4 = 4, 5 = 1, 6 = 2
1 = 8, 2 = 12, 3 = 8, 4 = 5, 5 = 10, 6 = 7
1 = 19, 2 = 12, 3 = 15, 4 = 11, 5 = 20, 6 = 23
1 = 38, 2 = 51, 3 = 31, 4 = 50, 5 = 36, 6 = 44
1 = 90, 2 = 87, 3 = 86, 4 = 82, 5 = 79, 6 = 76
1 = 175, 2 = 174, 3 = 160, 4 = 166, 5 = 153, 6 = 172
1 = 438, 2 = 396, 3 = 417, 4 = 406, 5 = 422, 6 = 421
1 = 835, 2 = 798, 3 = 875, 4 = 794, 5 = 877, 6 = 821
1 = 1580, 2 = 1661, 3 = 1631, 4 = 1774, 5 = 1776, 6 = 1578


## 5 Колода карт
### 5.1 Реалізація

In [28]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('K', '♣'), ('K', '♢'), ('K', '♡'), ('K', '♠'), ('10', '♣'), ('10', '♢'), ('10', '♡'), ('10', '♠'), ('7', '♣'), ('7', '♢'), ('7', '♡'), ('7', '♠'), ('5', '♣'), ('5', '♢'), ('5', '♡'), ('5', '♠'), ('3', '♣'), ('3', '♢'), ('3', '♡'), ('3', '♠'), ('9', '♣'), ('9', '♢'), ('9', '♡'), ('9', '♠'), ('6', '♣'), ('6', '♢'), ('6', '♡'), ('6', '♠'), ('J', '♣'), ('J', '♢'), ('J', '♡'), ('J', '♠'), ('2', '♣'), ('2', '♢'), ('2', '♡'), ('2', '♠'), ('4', '♣'), ('4', '♢'), ('4', '♡'), ('4', '♠'), ('8', '♣'), ('8', '♢'), ('8', '♡'), ('8', '♠'), ('1', '♣'), ('1', '♢'), ('1', '♡'), ('1', '♠'), ('Q', '♣'), ('Q', '♢'), ('Q', '♡'), ('Q', '♠')]


In [ ]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

2♡, 2♣, 2♠, 2♢, 9♡, 9♣, 9♠, 9♢, 10♡, 10♣, 10♠, 10♢, Q♡, Q♣, Q♠, Q♢, 7♡, 7♣, 7♠, 7♢, 8♡, 8♣, 8♠, 8♢, K♡, K♣, K♠, K♢, 6♡, 6♣, 6♠, 6♢, 5♡, 5♣, 5♠, 5♢, 1♡, 1♣, 1♠, 1♢, J♡, J♣, J♠, J♢, 4♡, 4♣, 4♠, 4♢, 3♡, 3♣, 3♠, 3♢


In [ ]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♡2, ♡9, ♡10, ♡Q, ♡7, ♡8, ♡K, ♡6, ♡5, ♡1, ♡J, ♡4, ♡3
♣2, ♣9, ♣10, ♣Q, ♣7, ♣8, ♣K, ♣6, ♣5, ♣1, ♣J, ♣4, ♣3
♠2, ♠9, ♠10, ♠Q, ♠7, ♠8, ♠K, ♠6, ♠5, ♠1, ♠J, ♠4, ♠3
♢2, ♢9, ♢10, ♢Q, ♢7, ♢8, ♢K, ♢6, ♢5, ♢1, ♢J, ♢4, ♢3


In [ ]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('K', '♠'), ('4', '♡'), ('7', '♢'), ('2', '♠'), ('6', '♣'), ('3', '♡'), ('7', '♠'), ('J', '♠'), ('J', '♣'), ('1', '♡'), ('4', '♢'), ('Q', '♣'), ('6', '♢'), ('K', '♡'), ('10', '♡'), ('2', '♡'), ('K', '♢'), ('8', '♠'), ('5', '♣'), ('9', '♡'), ('10', '♢'), ('10', '♠'), ('4', '♠'), ('J', '♡'), ('8', '♢'), ('6', '♠'), ('5', '♡'), ('9', '♣'), ('J', '♢'), ('6', '♡'), ('3', '♢'), ('9', '♢'), ('Q', '♢'), ('3', '♠'), ('4', '♣'), ('10', '♣'), ('9', '♠'), ('2', '♢'), ('K', '♣'), ('8', '♡'), ('1', '♢'), ('8', '♣'), ('3', '♣'), ('7', '♡'), ('5', '♠'), ('Q', '♠'), ('7', '♣'), ('1', '♣'), ('5', '♢'), ('Q', '♡'), ('1', '♠'), ('2', '♣')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [ ]:
# Місце для Вашого коду


### <font color=blue> 5.3 Задача </font>
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [84]:
#Домашнє завдання 2

np.random.shuffle(Cards)

def distribute(cards):
    suits = ['♢', '♠', '♣', '♡']
    suits_left = 4
    result = []
    
    cards = cards[:]
    
    for i in range(4):
        playerdict = {
            "♠": 0,
            "♡": 0,
            "♣": 0,
            "♢": 0
        }
        chosen_suit = np.random.randint(0, suits_left)
        playerdeck = []
        for card in cards[:]:
            card_suit = card[1]
            if card_suit == suits[chosen_suit] and playerdict[card_suit] < 4:
                playerdeck.append(card)
                cards.remove(card)
                playerdict[card_suit] += 1
            elif playerdict[card_suit] < 3:
                playerdeck.append(card)
                cards.remove(card)
                playerdict[card_suit] += 1
            else:
                continue
        print(playerdict)
        
        result.append(playerdeck)
        suits.remove(suits[chosen_suit])
        suits_left -= 1
        
    return result



count = 1

game_setup = distribute(Cards)

print("\n")

for player in game_setup:
    print(f"Player{count}: ", end="")
    for card in player:
        print(f"{card[0],card[1]}", end=", ")
    print("\b\b.\n")
    count += 1
                
            
        
    
        
        



{'♠': 4, '♡': 3, '♣': 3, '♢': 3}
{'♠': 3, '♡': 3, '♣': 3, '♢': 4}
{'♠': 3, '♡': 3, '♣': 4, '♢': 3}
{'♠': 3, '♡': 4, '♣': 3, '♢': 3}


Player1: ('6', '♢'), ('8', '♡'), ('1', '♡'), ('10', '♡'), ('8', '♣'), ('1', '♠'), ('9', '♠'), ('3', '♢'), ('9', '♢'), ('J', '♠'), ('9', '♣'), ('2', '♣'), ('7', '♠').

Player2: ('K', '♢'), ('K', '♡'), ('8', '♢'), ('5', '♣'), ('3', '♡'), ('7', '♣'), ('4', '♢'), ('6', '♡'), ('4', '♣'), ('3', '♠'), ('Q', '♠'), ('2', '♢'), ('2', '♠').

Player3: ('2', '♡'), ('9', '♡'), ('J', '♡'), ('1', '♣'), ('Q', '♢'), ('J', '♢'), ('10', '♢'), ('10', '♣'), ('6', '♣'), ('8', '♠'), ('K', '♠'), ('3', '♣'), ('10', '♠').

Player4: ('5', '♡'), ('Q', '♡'), ('4', '♡'), ('1', '♢'), ('J', '♣'), ('5', '♢'), ('Q', '♣'), ('6', '♠'), ('4', '♠'), ('7', '♢'), ('5', '♠'), ('7', '♡'), ('K', '♣').

